#!/bin/sh

# 设置简体中文
#uci set luci.main.lang=zh_cn
#uci commit luci

# 设置主机名称、时区
uci -q batch <<-EOF
	set system.@system[0].hostname='OpenWrt'
	set system.@system[0].timezone='CST-8'
	set system.@system[0].zonename='Asia/Shanghai'
EOF
uci commit system

# 修改后台地址、PPPOE拨号账号密码、加入網關 127.0.0.1
uci -q batch <<-EOF
	set network.lan.ipaddr='192.168.1.254'
	set network.lan.netmask='255.255.255.0'
	set network.lan.gateway='127.0.0.1'
	set network.wan.proto='pppoe'
	set network.wan.username='02985412735'
	set network.wan.password='a486200'
EOF
uci commit network

# 運行固件自動 pppoe 撥號
sed -i "s/2:-dhcp/2:-pppoe/g" /lib/functions/uci-defaults.sh

# 加入網關
#sed -i "/192.168.1.254/a\\\toption gateway '127.0.0.1'" /etc/config/network

# 取消自動訂閲節點，保留自動更新【GFW 列表和中国大陆 IP 段】
sed -i "s#/usr/bin/lua /usr/share/shadowsocksr/subscribe.lua#\#/usr/bin/lua /usr/share/shadowsocksr/subscribe.lua#" /usr/share/shadowsocksr/ssrplusupdate.sh

# 修改 Tailscale 常規設置（允許局域網訪問、禁用 MagicDNS）
sed -i "/option fw_mode/a\\\toption exit_node_allow_lan_access '1'\\
\toption disable_magic_dns '1'" /etc/config/tailscale

# 修改DNS
#uci set network.wan.peerdns='0'
#uci add_list network.wan.dns='114.114.114.114'
#uci add_list network.wan.dns='223.5.5.5'
#uci commit network

# 增加快速连接
#echo -n "net.ipv4.tcp_fastopen = 3" >> /etc/sysctl.conf

# 创建自己的防火墙表user
#echo 'nft delete table ip user' >>/etc/firewall.user
#echo 'nft add table ip user' >>/etc/firewall.user
#echo 'nft add chain ip user input { type filter hook input priority 0 \; policy accept \; }' >>/etc/firewall.user 
#echo 'nft add chain ip user FORWARD { type filter hook forward priority 0 \; policy accept \; }' >>/etc/firewall.user
# 劫持53端口流量，由路由器处理，科学上网更稳定
#echo 'nft add chain ip user PREROUTING { type nat hook prerouting priority dstnat \; policy accept \; }' >>/etc/firewall.user
#echo 'nft add rule ip user PREROUTING tcp dport 53 counter redirect to :53' >>/etc/firewall.user
#echo 'nft add rule ip user PREROUTING udp dport 53 counter redirect to :53' >>/etc/firewall.user
# 下面自定义防火墙规则
#echo 'nft insert rule ip user FORWARD ip daddr 192.168.1.209 meta hour "12:00"-"13:10" counter drop' >>/etc/firewall.user
#echo 'nft insert rule ip user FORWARD ip daddr 192.168.1.203 meta hour "01:00"-"18:05" counter drop' >>/etc/firewall.user
#echo 'nft insert rule ip user FORWARD ip daddr 192.168.1.203 meta hour "22:05"-"23:55" counter drop' >>/etc/firewall.user
#echo 'nft insert rule ip user FORWARD ip daddr 192.168.1.218 meta hour "02:00"-"23:55" counter drop' >>/etc/firewall.user
# 让防火墙调用script
#uci set firewall.userfirewall='include'
#uci set firewall.@include[-1].type="script"
#uci set firewall.@include[-1].path="/etc/firewall.user"
#uci set firewall.@include[-1].fw4_compatible="1"
#uci commit firewall
#/etc/init.d/firewall restart

# 配置DHCP和SSR+
mv /usr/share/linshi/dhcp /etc/config/
mv /usr/share/linshi/shadowsocksr /etc/config/
mv /usr/share/linshi/china_ssr.txt /etc/ssrplus/
mv /usr/share/linshi/gfw_list.conf /etc/ssrplus/
#mv /usr/share/linshi/passwall /etc/config/
#mv /usr/share/linshi/passwall2 /etc/config/
#mv /usr/share/linshi/homeproxy /etc/config/
#mv /usr/share/linshi/nft-qos /etc/config/

# 優化SSR Plus+自動更新订阅的 小時:分鐘 XX點XX分
#sed -i 's/0 \$(uci_get_by_type/51 \$(uci_get_by_type/' /etc/init.d/shadowsocksr

sed -i 's/o:value(t, t .. ":00")/o:value(t, t .. "")/' /usr/lib/lua/luci/model/cbi/shadowsocksr/servers.lua
sed -i 's/o:value(i, i .. ":00")/o:value(i, i .. "")/' /usr/lib/lua/luci/model/cbi/shadowsocksr/servers.lua

#sed -i 's/auto_update", "1/auto_update", "0/g‘  /usr/lib/lua/luci/model/cbi/shadowsocksr/servers.lua

# 加入啓動項
#sed -i "/exit 0/i \	ethtool -s eth0 speed 2500 duplex full\n	ethtool -s eth1 speed 2500 duplex full\n" /etc/rc.local

# 修复SSR Plus+不能订阅V2RAY机场有alterid>0的v2ray节点
#sed -i "/document.getElementsByName('cbid.shadowsocksr.' + sid + '.server_port')\[0\].value = ssm.port;/a\ \t\t\tdocument.getElementsByName('cbid.shadowsocksr.' + sid + '.alter_id')\[0\].value = ssm.aid; " /usr/lib/lua/luci/view/shadowsocksr/ssrurl.htm
#line=`sed -n '/if info.aid and (tonumber(info.aid) > 0) then/=' /usr/share/shadowsocksr/subscribe.lua `
#sed -i "${line},$((${line}+2))d" /usr/share/shadowsocksr/subscribe.lua
#sed -i "/result.v2ray_protocol = 'vmess'/a\ \t\tresult.alter_id = info.aid" /usr/share/shadowsocksr/subscribe.lua
#sed -i '/-- VmessId/i -- AlterId\no = s:option(Value, "alter_id", translate("AlterId"))\no.datatype = "port"\no.default = 16\no.rmempty = true\no:depends({type = "v2ray", v2ray_protocol = "vmess"})' /usr/lib/lua/luci/model/cbi/shadowsocksr/client-config.lua
#sed -i '/id = server.vmess_id,/a\ \t\t\t\t\t\talterId = (server.v2ray_protocol == "vmess" or not server.v2ray_protocol) and tonumber(server.alter_id) or nil,' /usr/share/shadowsocksr/gen_config.lua

# 修改后台登陆的缺省密码为password
#sed -i 's/root::0:0:99999:7:::/root:$1$V4UetPzk$CYXluq4wUazHjmCDBCqXF.:0:0:99999:7:::/g' /etc/shadow
#sed -i 's/root:::0:99999:7:::/root:$1$V4UetPzk$CYXluq4wUazHjmCDBCqXF.:0:0:99999:7:::/g' /etc/shadow

sed -i 's#root:::0:99999:7:::#root:$5$qY781.vtG9/2AHhK$QHezq5zRqwAunTctzGwLhDHfYfsrBiY9qeSxymZCaU6:20086:0:99999:7:::#g' /etc/shadow
sed -i 's#root::0:0:99999:7:::#root:$5$qY781.vtG9/2AHhK$QHezq5zRqwAunTctzGwLhDHfYfsrBiY9qeSxymZCaU6:20086:0:99999:7:::#g' /etc/shadow

# vlmcsd 服務缺省為激活運行狀態
#sed -i "s#option enabled '0'#option enabled '1'#" /etc/config/vlmcsd
#sed -i "s#option auto_activate '0'#option auto_activate '1'#" /etc/config/vlmcsd

exit 0
